# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-23 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestorObjetos', '0002_auto_20180123_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='grupos',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
