# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-01-23 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorObjetos', '0005_auto_20180123_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repositorio',
            name='grupos',
            field=models.ManyToManyField(blank=True, null=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
