# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-11 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestorObjetos', '0007_objeto_proyecto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='especificacionlom',
            name='lc1_cobertura',
        ),
        migrations.RemoveField(
            model_name='especificacionlom',
            name='lc1_nivel_agregacion',
        ),
        migrations.RemoveField(
            model_name='especificacionlom',
            name='lc3_instrucciones',
        ),
        migrations.RemoveField(
            model_name='especificacionlom',
            name='lc3_requerimientos',
        ),
        migrations.RemoveField(
            model_name='especificacionlom',
            name='lc4_contexto',
        ),
        migrations.RemoveField(
            model_name='especificacionlom',
            name='lc4_nivel_inter',
        ),
        migrations.RemoveField(
            model_name='especificacionlom',
            name='lc4_poblacion',
        ),
        migrations.RemoveField(
            model_name='especificacionlom',
            name='lc4_tipo_inter',
        ),
        migrations.RemoveField(
            model_name='especificacionlom',
            name='lc6_uso_educativo',
        ),
        migrations.RemoveField(
            model_name='objeto',
            name='proyecto',
        ),
    ]
