# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-18 15:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestorObjetos', '0008_auto_20180211_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='repositorio',
            field=models.ForeignKey(help_text='Carrera/Facultad donde se aloja el objeto', on_delete=django.db.models.deletion.CASCADE, to='gestorObjetos.Repositorio'),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='nombre',
            field=models.CharField(help_text='Nombre que identifica a la facultad', max_length=200, unique=True, verbose_name='Nombre de la facultad'),
        ),
        migrations.AlterField(
            model_name='repositorio',
            name='publico',
            field=models.BooleanField(default=True, help_text='Marca para habilitar la facultad al público', verbose_name='Público'),
        ),
    ]
